<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./github.gltf -T -t
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { RoundedBoxGeometry, useGltf } from '@threlte/extras';
	import IconBox from './IconBox.svelte';

	type $$Props = Props<THREE.Group & { link: string }>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Curve: THREE.Mesh;
		};
		materials: {
			['SVGMat.001']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/github-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();

	export let link = 'https://github.com/flo-bit';
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Curve.geometry} scale={4} rotation.x={Math.PI / 2}>
			<T.MeshStandardMaterial color="#06b6d4" metalness={0.9} roughness={0.2} />
		</T.Mesh>

		<IconBox {link} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
